#!/usr/bin/env bash
# what stops ubuntu nginx from listening on port 80?
# configures nginx to run an listen on port 80.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
